import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { ROUTS_CONSTANTS } from "@/constants/routs.constants";
import { LINKS_CONSTANTS } from "@/constants/links.constants";
import { FaGithub, FaLinkedin, FaTelegram, FaInstagram } from "react-icons/fa";
import { FiMail } from "react-icons/fi";
import Header from "@/components/header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Header />
        {children}

        <footer className="flex flex-col items-center gap-6 bg-tertiary px-4 py-8 text-center sm:px-8 md:flex-row md:justify-between md:gap-4 md:px-16 md:py-4 md:text-left">
          <Link href={ROUTS_CONSTANTS.ROOT} className="shrink-0">
            LOGO
          </Link>

          <nav className="flex flex-row items-center gap-4">
            <Link href={LINKS_CONSTANTS.GITHUB} aria-label="GitHub">
              <FaGithub size={24} strokeWidth={1.5} />
            </Link>
            <Link href={LINKS_CONSTANTS.LINKEDIN} aria-label="LinkedIn">
              <FaLinkedin size={24} strokeWidth={1.5} />
            </Link>
            <Link href={LINKS_CONSTANTS.TELEGRAM} aria-label="Telegram">
              <FaTelegram size={24} strokeWidth={1.5} />
            </Link>
            <Link href={LINKS_CONSTANTS.INSTAGRAM} aria-label="Instagram">
              <FaInstagram size={24} strokeWidth={1.5} />
            </Link>
            <Link href={LINKS_CONSTANTS.EMAIL} aria-label="Email">
              <FiMail size={24} strokeWidth={1.5} />
            </Link>
          </nav>

          <p className="text-sm md:text-base">
            &copy; {new Date().getFullYear()} Ihor. All Rights Reserved.
          </p>
        </footer>
      </body>
    </html>
  );
}
